on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generate Arctype Debian package
      run: |
        sudo apt install checkinstall -y
        arctypeversion=$(echo ${{github.ref}} | sed "s/refs\/tags\/v//")
        ./build.sh
        cp ./arctype_${arctypeversion}-1_amd64.deb /tmp/arctype_amd64.deb

    - name: Upload Arctype Debian package
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: /tmp/arctype_amd64.deb
        asset_name: arctype_amd64.deb
